### ISSUE TITLE
[Bug]: 4.5 broke compatiblity with Vanilla Armour Expanded

### ISSUE THREAD

**Issue by garret-gunter** [CombatExtended-Continued/CombatExtended#1359] opened 2022-02-13 04:09 UTC
**Specifications**
Rimworld version: 1.3.3200 rev726
Combat Extended version: 4.5 (1.3.4.5)
Combat Extended source: Steam
Your operating system: Windows 10
Your mod list:
```
[Mod list length: 10]
Harmony
Core
Royalty
Ideology
HugsLib
Combat Extended
Combat Extended Guns
Combat Extended Melee
Vanilla Expanded Framework
Vanilla Armour Expanded
```

**Description**
On game launch Hugs logs has this error `Could not resolve cross-reference to Verse.ApparelLayerDef named MiddleHead (wanter=layers)`.  

As far as I can tell this is probably an issue that needs to be resolved on the side of `Vanilla Armour Expanded`.  That mod contains a patch for Combat Extended that contains a reference to `MiddleHead`.  The file is `\1.3\Patches\Royalty.xml` within the Vanilla Armour Expanded mod's directory.

**Expected behavior**
No errors show up in the log.

**To reproduce**
Install the mods I listed and the error will show up after the game reaches the main menu.

**Screenshots & log dumps**
Here is the log when only the listed mods were active: https://gist.github.com/HugsLibRecordKeeper/b66397d5d8e547fcb5e3816843692e1d

I also have other mods installed and the error was first discovered when running all of my mods.  Here is the log with all of my mods installed: https://gist.github.com/HugsLibRecordKeeper/23ebab26ab87c38d5ca63c3575c266c7

Link to Vanilla Armour Expanded: https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by garret-gunter** [comment] 2022-02-13 04:11
I couldn't pick if this was a bug or a patch request.  I went with bug since there is already a patch for Vanilla Armour Expanded.

**Comment by amaotoUsagi** [comment] 2022-02-14 03:33
Hard to say, but youre better off telling it to the Vanilla Expanded Team. As Vanilla Armour Expanded has a Built-in CE patch for the Prestige armors thats still using MiddleHead layer.

**Comment by Lamarcke** [comment] 2022-02-18 03:29
Facing the same issue.

**Comment by ItsSamGray** [comment] 2022-02-19 10:11
This issue is caused by an outdated internal patch inside the VAE files and must be resolved by the VE team themselves.

**Closed by ItsSamGray** 2022-02-19 10:11 UTC
Labels: Bug
