### ISSUE TITLE
[Discussion]: Ideas for Combat Extended Achievements

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#370] opened 2020-11-16 04:47 UTC
With the release of Vanilla Achievements Expanded, I think some Combat Extended achievements may be in order. The actual feasibility of these ideas within the framework will have to be determined later, but this post is for suggestions.

**Stay With Me!** - Stabilize a wounded pawn with less than 0.25 hours to live.

**You Cannot Hide** - Spot a target using binoculars.

**Game Over, Man!** - Have a colonist become shell-shocked.

**Blood for the Blood God!** - Have a colonist enter a combat frenzy.

**Steel Rain** - Kill 100 enemies with mortars.

**Napalm Sticks to Raiders** - Have 10 enemies on fire at the same time.

**Suppressing Fire** - Have 10 enemies under heavy suppression at the same time.

**Anti-Armor** - Kill a Centipede.

**A Good Start** - Craft 10,000 rounds of ammunition.

**Well Stocked** - Craft 100,000 rounds of ammunition.

**Bullet Farm** - Craft 500,000 rounds of ammunition.

**Comment by Peckun** [comment] 2020-11-16 05:56
**Thats a nice head on your shoulder.** - Obliterate a pawn's head with one shot/strike.
**Heavy Armaments** - Equip a pawn with a heavy weapon/armor.
**LMG go brrr** - Empty a LMG weapon with suppression mode.

**Comment by Safairette** [comment] 2020-11-16 07:55
**Guaranteed extinction** - create an explosion more than 25 cells wide
**Barely alive** - survive a direct HCB hit
**Lock 'n load!** - reload a total of 100 times
**Unfortunate circumstance** - blow yourself up with your own grenade
**Not even a scratch** - completely defect 50 bullets with armor

**Comment by Amondaet** [comment] 2020-11-16 08:05
**Mow them down** - down 5 enemy pawns with a single volley of automatic weapon.
**More blood soaks the soil** - Down without killing 20 enemies at the same time.

**Comment by gsrutkowski** [comment] 2020-11-16 13:12
**We Need Guns*** - Research Gunsmithing
**I want to see the real guns** - Research Blowback Operations
**I said, I want to see the real guns** - Research Gas Operation
**Perfection, the real guns** - Research Precision Rifiling
**Distant Doom Metal sounds** - Equip a psychopath pawn with Power Armor, Power Armor Helmet, and a Shotgun.
**The ones who run are well disciplined Raiders** - Assault a tribal settlement while using LMGs
**Distant Fortunate Son** - Assault a tribal base while using LMGs, Assault Rifles, Flak armor, and having at least one pawn with a Title
**A Snail crawling along the edge of a razor** - Have a pawn breakdown during a Raid

**Comment by sumghai** [comment] 2020-11-19 04:38
> **Thats a nice head on your shoulder.** - Obliterate a pawn's head with one shot/strike.
Extending this a bit further
**Hat Trick** - Obliterate a pawn's head with one shot/strike, three times

**Comment by AluminumAlman** [comment] 2020-11-29 10:38
**Bee-Keeper** - Cause 100 insectoids (over the duration of the game) to begin wandering aimlessly with the use of smoke.
**Achille's Heel** - Have your pawn kill another pawn with power armor by using a medieval tech weapon.
**Wrong Side of the Bed** - Witness a humanoid pawn getting directly hit by an explosive projectile.
**Nature Versus Technology** - Have a tamed animal kill a mechanoid.
**Cracked Like an Egg** - Have a centipede's heavy charge blaster's projectile deflect off a pawn's helmet.
**Duck and Weave** - Have a pawn dodge 10 bullets in a row by moving to the sides.
**Inhuman Reflexes** - Have a pawn dodge 30 bullets in a row by moving to the sides.
**Improper Weapons Storage** - Have no less than 10 cells worth of explosives or ammunition blow up/cook up in quick succession.
**Pants Delivery Service** - Strip a downed raider of their undamaged flak pants.
**Commencing Barrage** - Fire 20 mortars in quick succession.
**Shockingly Effective** - Have a raider enter pain shock due to electrical burns.

**Comment by heavenisaplaceonearth1** [comment] 2020-12-22 12:30
**Nukes, knives, sharp sticks...** - Craft a weapon from each technology level.
**Mann Vs Machine** - Have a colonist take down a Centipede singlehandedly.
**White Death** - Have a colonist kill 259 raiders with a rifle.
**Sneering Imperialist** - Destroy a Tribal Settlement.
**Fight the Power!** - Destroy an Empire Settlement.
**Misericorde** - Finish off a downed enemy in power armor.
**Half-Sword** - Down an enemy in power armor using only a sword.
**Medic!** - Have a colonist stabilize 100 times. 
**Zakhaev-ed** - blow off a raider's arm using a .50 BMG rifle.
**ER Residency** - Have a colonist stabilize 1000 times.
**Kingslayer** - Kill an enemy leader.
**Colt made them equal** - Have a colonist kill an enemy equipped with the same weapon.
**Less than lethal** - Kill 100 stunned raiders.
**Iran–Contra affair** - sell 86 M72 LAWs.
**Push it to the Limit** - have a colonist take out an outpost singlehandedly while high on yayo.
**Ave, True to Caesar** - kill 100 outlanders using only gladii.
**Custom Tooled Cartridges** - research specialized ammunition
**one firearm for every twelve people on the planet** - sell 550 firearms.
**Max Payne** - have a colonist kill 100 raiders while having an alcohol addiction.
**HIgh on your own supply** - have a colonist kill 100 raiders while having a yayo addiction.
**Let them Burn** - down 1000 raiders using flame weapons.
**They're coming out of the goddamn walls!** - destroy an insectoid infestation within your colony.
**They mostly come out at night** - destroy an insectoid infestation between 0000 and 0600.
**Conscripted** - Have a colonist with no passion in Shooting kill 100 raiders.
**Russia's greatest export** - sell 100 AK-47s.
**Accept no substitutes** - craft a legendary AK-47.
**Calm Nerves** - Have a colonist kill a raider while drunk.
**Ho Chi Minh trail** - sell 50 AK-47s to tribal settlements or tribal trade caravans.
**Kept for Close Encounters** - kill 100 insectoids with 12 gauge weapons
**phased plasma rifle in the 40 watt range** - research pulse-charged munitions
**Marines make do** - kill 100 raiders using an "Awful" quality weapon.
**polished to a mirror sheen** - make a legendary 1911.
**Smoke em if you got em** - throw 100 smoke grenades.
**LMG mounted and loaded** - have a single colonist kill 6 raiders with a Degtyarev DP.
**Coriolis effect** - have a colonist hit a raider 49+ tiles away.
**MLG** - have a colonist hit a raider 0-8 tiles away using an .50 BMG weapon.
**Knife to a Gunfight** - have a colonist kill an armed raider with a knife
**Feeling Lucky, Punk?** - craft a legendary ruger redhawk. 
**Fireflower** - have a pawn sow 100 blazebulbs
**Combat Engineer** - have a pawn construct 100 embrasures. 
**Basic combat loadout** - have a pawn carry 210 5.56mm bullets
**Designated Can Opener** - have a pawn kill 10 centipedes.
**Blue on blue** - down a friendly colonist due to friendly fire
**Heartbreaker** - destroy 100 hearts with a firearm.
**Quicker then alcohol** destroy 100 livers with a firearm.
**Danger close** - hit a friendly pawn with your own mortar shells.
**Ladykiller** - have one male colonist kill 100 female pawns
**Black Widow** - have one female colonist kill 100 male pawns
**Cherchez La Femme** - have one female colonist kill 100 female pawns
**Confirmed Bachelor** - have one male colonist kill 100 male pawns
**Yayo's Combat 3** - have a colonist kill 10 raiders while overdosing on yayo
**Breathtaking** - have 10 raiders die due to smoke inhalation. 
**Econ Round** - craft a legendary Tec DC-9.
**Overkill** - kill 100 raiders by destroying their torsos
**Royal Guard** - have a single colonist perform 100 parries
**MY LEG!** - destroy 100 legs attached to raiders.
**If it ain't broke...** - kill 100 mechanoids using industrial level weaponry.
**Artillery Only** - construct 10 mortars. 
**To whom it may concern** - research advanced launchers.
**Logistical nightmare** - craft 1000 rounds of 10 different calibers.

**Comment by Arcalane** [comment] 2021-01-07 15:13
Some simple-ish gimmicky ones;  
**Terminated** - have a heavily-augmented colonist disable or destroy a certain number of androids or mechanoids using any shotgun  
**Assault Tactics** - have a colonist kill an enemy with a melee weapon attack shortly after using a jump pack or teleporting with a *skip* psycast  
**Get Over Here!** - have a colonist kill an enemy with a melee weapon attack shortly after teleporting *the victim* with a *skip* psycast
**Rules of Nature** - have a colonist land the killing blow on a Centipede with a bladed melee weapon  
**Crowd Controller** - kill a certain number of pawns whilst they're under at least one negative status effect such as burning, blind, stun, toxic buildup, EMP, etc.  
**Out Of Their Misery** - kill an enemy pawn that is currently suffering from at least three *different* negative status effects at once  
**Merciful** - finish off a certain number of downed humanoids that are bleeding out  
**I Don't Keep It Loaded, Son** - have a colonist with cryptosleep sickness equip a pistol  
**Ain't Got Time To Bleed** - have colonists who are currently at risk of bleeding out kill a certain number of enemies  
**Tank \*This!\*** - flatten a Centipede with a direct hit from the 90mm flak turret HEAT ammo  
**Life's Just One Big Minefield** - kill a certain number of raiders using traps such as IEDs and landmines  
**Counter-Battery Fire** - destroy a raiding party's siege weapon using your own mortar or artillery fire  
**An Elegant Weapon** - acquire a high-quality plasma sword (or wraith blade from CE: Melee)  
**A More Civilized Age..?** - have colonists kill a certain number of enemies with spacer/archo -tech melee weapons (zeushammer, CE:Melee power weapons, plasma sword, etc.)

**Closed** 2024-03-13 23:41 UTC
Labels: Compatibility, Feedback, Discussion
