### ISSUE TITLE
[Bug]:Can shoot enemies in melee range

### ISSUE THREAD

**Issue by Yeetedfetus** [CombatExtended-Continued/CombatExtended#1965] opened 2022-10-26 20:09 UTC
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3.3287
Combat Extended version: 1.3.4.9.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list:
        brrainz.harmony
        ludeon.rimworld
        vanillaexpanded.backgrounds
        unlimitedhugs.hugslib
        brrainz.achtung
        oskarpotocki.vanillafactionsexpanded.core
        oskarpotocki.vfe.insectoid
        ceteam.combatextended

**Description**
Provide a concise description of the issue or concern. What happened?
If an enemy is in melee range I can right click them and pick 'Fire at (enemy)' and the pawn will shoot in melee range

**Expected behavior**
What did you expect to happen?
Not to be able to shoot in melee range

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Open a colony and ideally spawn an infestation and get a pawn with a ranged weapon in melee range with the insects and then right click them and choose fire at

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment] 2022-10-26 23:45
Closing this, as it's a duplicate of #1693.

**Closed by N7Huntsman** 2022-10-26 23:45 UTC
Labels: Bug
