### ISSUE TITLE
[Bug]: Power armour fails to protect against toxic fallout.

### ISSUE THREAD

**Issue by irRegularGuy646** [CombatExtended-Continued/CombatExtended#2727] opened 2023-08-29 18:35 UTC
**Specifications**

Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.4-hotfix.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10

Your mod list: 
Harmony
Core
Combat Extended

**Description**
Pawns get the "Toxic buildup" hediff while outside during toxic fallout despite having 100% toxic environment resistance from a full set of power armour + helmet, and the severity of the hediff actually increases faster than a pawn with 0% resistance.

**Expected behavior**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/71989367/9dc93c60-371a-4198-927d-3f4542a918b2)
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/71989367/8faa9818-d2cc-48c6-a5e3-32233d9b3690)

**To reproduce**
1. Force a pawn to wear a full set of power armour
2. Have them stand outside with toxic fallout

**Screenshots & log dumps**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/71989367/c10f3f10-14d7-42c2-ad94-1610d612ad24)
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/71989367/19789b90-6aef-4406-92a9-f2a43cd81000)
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/71989367/b9eaf113-4a1c-4a11-9d90-0be0321e40ff)
https://pastebin.com/LdgufKUS

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by skycrossercat** [comment] 2023-08-30 05:13
Something must be wrong on your end, I let one guy wear full set power armor and stand in toxic fallout for a day, and he get no toxic buildup at all (the guy next to him has no mask, get almost 40% buildup).

**Comment by irRegularGuy646** [comment] 2023-08-30 17:21
what version are you using? what's your mod list?

**Comment by SamaelGray** [comment] 2023-08-30 17:46
Start looking for the culprit with the binary search method, items that give toxic resistance work as intended.

**Comment by irRegularGuy646** [comment] 2023-08-31 01:05
i'm not sure what you mean by that. i've tested both power armour and gas masks and neither provide anywhere near the resistance they say they do, and i did the testing with only harmony, core and CE

**Comment by skycrossercat** [comment] 2023-08-31 03:25
Well, I guess I understand what you mean, since Vanilla has the `<ToxicResistance>`  removed from power armor, and make the `<ToxicEnviormenntResistance>` as a replacement of it, which is from Biotech. In my test pawns with protection gears have a little bit slower build up if Biotech is not loaded, when Biotech is loaded then they function just fine.

**Comment by skycrossercat** [comment] 2023-08-31 03:29
Can confirm this, though I am not sure if this one is one CE side, or just another shitty example of base function locked behind DLC. (I remember vanilla power armor used to have some degree of toxic fallout protection although not being fully protected, now it's just totally gone

**Comment by irRegularGuy646** [comment] 2023-08-31 03:30
guhh

**Comment by skycrossercat** [comment] 2023-08-31 03:52
> guhh

You notice this becasue you don't have Biotech and encountered toxic fallout? Then congrats, you can only be a sitting duck in your base until it's gone.
And I can again confirm that same result would happen in vanilla, those poor guys don't know the mod adding toxic resistance to PA would be no use unless they have Biotech (the value is marked as `MayRequire="Ludeon.RimWorld.Biotech"` for vanilla war veil).
(I don't think Toxic fallout event is locked behind Biotech since it's not marked as one, so this is like a nerf to vanilla only players just because the DLC released

**Closed** 2024-11-27 03:05 UTC
Labels: Bug
