### ISSUE TITLE
[Bug]: VFE - Pirates Patch Operation Failed

### ISSUE THREAD

**Issue by foul-fortune-feline** [CombatExtended-Continued/CombatExtended#1870] opened 2022-09-19 00:22 UTC
**Specifications**
Rimworld version: 1.3.3389
Combat Extended version: 1.3.4.8.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Solus 4.3 Fortitude
Your mod list:
- Harmony
- Core
- Vanilla Expanded Framework
- Vanilla Factions Expanded - Pirates
- Combat Extended

**Description**
Debug messages state CE patch operation has failed on Vanilla Factions Expanded - Pirates (thrice)

**Expected behavior**
Game loads without errors

**To reproduce**
Open game with CE, VFE - Pirates, and dependencies

**Screenshots & log dumps**
https://justpaste.it/2zcje

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment] 2022-09-19 10:59
Already fixed in the dev build, caused by not having the Ideology DLC installed.

**Closed by ItsSamGray** 2022-09-19 10:59 UTC
Labels: Bug
