### ISSUE TITLE
[Bug]:Kijin 2.0 purple texture issue with masks

### ISSUE THREAD

**Issue by yanzco** [CombatExtended-Continued/CombatExtended#106] opened 2020-05-28 04:47 UTC
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 
Combat Extended version: Combat Extended 2.1 – “Only Most Dead!”
Your mod list: Combat Extended, FemaleBB BodyType Support, Kijin 2.0, Aparello 2

**Description**
Provide a concise description of the issue or concern. What happened?
Purple Texture appears because of missing textures

**Expected behavior**
What did you expect to happen?

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
wear a gasmask / hat

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

```

Failed to find any textures at Hats/Gas_Female while constructing Multi(.....)
Failed to find any textures at Hats/Kurt_Female while constructing Multi(.....)
Failed to find any textures at Things/Pawn/Humanlike/Apparel/CowboyHat/CowboyHat_Female while constructing Multi(.....)
Failed to find any textures at Hats/Kurtlight_Female while constructing Multi(.....)

```

edit: also happened to other race mods like orassans, that have FemaleBB BodyType Support
vanilla humans that has bodytype of FemaleBB Bodytype Support also gets purple textures when wearing head gears with Combat extended...

and when Combat Extended is removed, all is well..

so i guess, it is really with CE and FemaleBB BodyType Support

As stated in FemaleBB BodyType Support that loading it before CombatExtended will fix purple textures..but it does nothing..

**Complete the following checklist**
I hereby verify that I have done the following:
- [ /] Confirmed that my game version and load order are correct.
- [ /] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ /] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ /] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by skycrossercat** [comment] 2020-05-28 07:28
I think the purple square issue also happens to them when they are wearing hats in 'middle head' layer, can you test it for me to confirm the issue?

**Comment by yanzco** [comment] 2020-05-28 08:10
yes confirmed, also wearing hats does the purple texture..
yet if i disable all hats with "hide hats". the kijins are fine.. but everyone's hats / mask / headgear graphics dissapears.. :(

**Comment by N7Huntsman** [comment] 2020-05-29 05:30
I'm marking this as a duplicate of #79 but will leave it open since the it's got some useful information.

**Closed** 2020-09-11 03:34 UTC
Labels: Bug, Duplicate
