### ISSUE TITLE
[Bug]: Tac vests from some materials not rendering properly

### ISSUE THREAD

**Issue by T-rexsuper1** [CombatExtended-Continued/CombatExtended#2100] opened 2022-11-23 17:20 UTC
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: Novermber 20 workshop upload. 
Combat Extended source (Steam, GitHub, etc.): Workshop
Your operating system: Win 10
Your mod list:
Harmony
Core
DLC
Hugslib
CE

**Description**
Provide a concise description of the issue or concern. What happened?
Very hard to explain the nature of this bug and also very hard to find which materials cause it because it seem to happen at random with random materials. I cannot provide a specific list of materials because it simply is not consistent. The issue is  TacVests fail to render above parka and (probably) other clothing for shell layer. Which causes them to render behind literally everything, only slightly visible from side view. 
**Expected behavior**
What did you expect to happen?
Tac vests should, and sometimes do, as they should, render above parkas and (probably) other shell clothing. 
**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Honestly I have no idea. Just spawn a bunch of tacvests from random materails, wear a parka and see what breaks it. 
![image](https://user-images.githubusercontent.com/30936470/203609355-6d96206a-f06a-4a3d-9ebe-94be84e5c7b6.png)

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by albertbokor** [comment] 2023-01-02 19:24
Made tacvest not stuffable, still happnes.
For a while it seemed as if behavior doesnt happen with CutoutCompex shader type clothes but then it did.

**Comment by N7Huntsman** [comment] 2024-11-27 02:53
Likely a duplicate of #1817

**Closed by N7Huntsman** 2024-11-27 02:53 UTC
Labels: Bug
